### ISSUE TITLE
Add Higher-Order Components Example and info 

### ISSUE THREAD

**Issue by Swap76** [Swap76/ReactJSBasics#17]
Create a new file named Higher-Order-Components in docs and add the following:

- Where to use Conditional Rendering 

- How to use Higher-Order-Components (Code with Higher-Order-Components)

- More info if there and make a request to open API with Higher-Order-Components

If anyone is taking the issue please comment to save efforts of others

Make .md file in docs as we are shifting the repo to docsify

**Comment by SohamChhapre** [comment]
i am working on it

**Comment by Swap76** [comment]
@SohamChhapre Looking forward to seeing the work
