### ISSUE TITLE
Add React Forms Example with info in docs as .md file

### ISSUE THREAD

**Issue by Swap76** [Swap76/ReactJSBasics#19]
Give Example of React Forms the code should follow ES6 Standerds

Need the file in reactForms.md explaning about React Forms and how to use it

If you are working on it please comment here

**Comment by Tamy123** [comment]
Can i take this too?

**Comment by jblancoh** [comment]
i take it

**Comment by Swap76** [comment]
@Tamy123 Will assign the issue to you go ahead with the work

**Comment by Tamy123** [comment]
Okay great! I have started working on it
