### ISSUE TITLE
Add Flux Concepts with info

### ISSUE THREAD

**Issue by Swap76** [Swap76/ReactJSBasics#20]
Add info about Flux concepts and add the following things also

- Actions
- Dispatcher
- Store 
- View

**Comment by wander-igdst** [comment]
@Swap76  Working on this!

**Comment by Swap76** [comment]
@wander-igdst Assigned to you

**Comment by wander-igdst** [comment]
Hi @Swap76 

How should I login to the app to test stuff? I could see the email password being validated with https://cors-anywhere.herokuapp.com/http://siesgst.edu.in/agnostech/login. Please help with the same.

**Comment by Swap76** [comment]
@wander-igdst Sorry the validation is just for prototyping please remove it or keep it there and add the flux concept outside in login

**Comment by wander-igdst** [comment]
Okay sure, thanks for the clarification
