### ISSUE TITLE
Compilation warning due to map callback function not returning a value

### ISSUE THREAD

**Issue by wander-igdst** [Swap76/ReactJSBasics#26]
<img width="1245" alt="Screen Shot 2019-10-16 at 9 20 54 AM" src="https://user-images.githubusercontent.com/56194378/66887987-87c1d380-effa-11e9-9f1b-b3a5d8c47211.png">

As map callback function is supposed to return a value, and the use case here is not suitable to use map. Hence we need to use for each function for the same.

**Comment by fcosueza** [comment]
Seems like this is fixed in #27

**Comment by Swap76** [comment]
@fcosueza Thanks :-)
