### ISSUE TITLE
Create Basic component for example

### ISSUE THREAD

**Issue by Swap76** [Swap76/ReactJSBasics#9]
Create a new component integrate into the app 

the component should be combination of 2-3 small components

Add Comments also for newbies to understand

**Comment by donycisneros** [comment]
Can I be assigned to this?

**Comment by Swap76** [comment]
@donycisneros you can start working on this I want the index.js to have only 3 components according to combine the components

**Comment by Tamy123** [comment]
Assign this too?

**Comment by Swap76** [comment]
@Tamy123 Looking forward to the work :-)

**Comment by Tamy123** [comment]
Done please check the PR
